// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"

// names.cpp
cpp11::writable::strings tzdb_names_cpp();
extern "C" SEXP _tzdb_tzdb_names_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(tzdb_names_cpp());
  END_CPP11
}
// path.cpp
void tzdb_set_install_cpp(const cpp11::strings& path);
extern "C" SEXP _tzdb_tzdb_set_install_cpp(SEXP path) {
  BEGIN_CPP11
    tzdb_set_install_cpp(cpp11::as_cpp<cpp11::decay_t<const cpp11::strings&>>(path));
    return R_NilValue;
  END_CPP11
}
// version.cpp
cpp11::writable::strings tzdb_version_cpp();
extern "C" SEXP _tzdb_tzdb_version_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(tzdb_version_cpp());
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _tzdb_tzdb_names_cpp();
extern SEXP _tzdb_tzdb_set_install_cpp(SEXP);
extern SEXP _tzdb_tzdb_version_cpp();

static const R_CallMethodDef CallEntries[] = {
    {"_tzdb_tzdb_names_cpp",       (DL_FUNC) &_tzdb_tzdb_names_cpp,       0},
    {"_tzdb_tzdb_set_install_cpp", (DL_FUNC) &_tzdb_tzdb_set_install_cpp, 1},
    {"_tzdb_tzdb_version_cpp",     (DL_FUNC) &_tzdb_tzdb_version_cpp,     0},
    {NULL, NULL, 0}
};
}

void api_init(DllInfo* dll);

extern "C" void R_init_tzdb(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  api_init(dll);
  R_forceSymbols(dll, TRUE);
}
