# Generated by cpp11: do not edit by hand

tzdb_names_cpp <- function() {
  .Call(`_tzdb_tzdb_names_cpp`)
}

tzdb_set_install_cpp <- function(path) {
  invisible(.Call(`_tzdb_tzdb_set_install_cpp`, path))
}

tzdb_version_cpp <- function() {
  .Call(`_tzdb_tzdb_version_cpp`)
}
