on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Which operating system to debug on'
        required: true
        default: 'ubuntu-18.04'
        type: choice
        options:
        - macOS-latest
        - windows-latest
        - ubuntu-18.04
      r_version:
        description: 'Which R version to debug on'
        required: true
        default: 'release'
        type: choice
        options:
        - devel
        - release
        - oldrel-1
        - oldrel-2
        - oldrel-3
        - oldrel-4

name: debug

jobs:
  debug:
    runs-on: ${{ github.event.inputs.os }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ github.event.inputs.r_version }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, local::.
          needs: check

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
